### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by ntrphongse** [nghminh163/MessengerStranger#3]
![image](https://user-images.githubusercontent.com/57389575/72723142-91874400-3bb2-11ea-8c81-472dfa46ff39.png)
Sao mình chạy thì nó ra như vầy vậy bạn?

**Comment by phamleduy04** [comment]
Hosting chạy chỉ nhận POST request chứ k nhận GET request

**Comment by phamleduy04** [comment]
@nghminh163 close issue đi b
